<?php

/**
 * @file
 * Define some plugin systems to test Plugin Helper plugin includes.
 */

/**
 * Implementation of hook_plugin_manager_plugin_directory().
 */
function plugin_manager_plugin_test_plugin_manager_plugin_directory($module, $plugin) {
  if ($module == 'plugin_manager_plugin_test') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_autoload_info().
 */
function plugin_manager_plugin_test_autoload_info() {
  return array(

  );
}

/**
 * Implements hook_plugin_manager_plugin_type().
 */
function plugin_manager_plugin_test_plugin_manager_plugin_type() {
  return array(
    'extra_defaults' => array(
      'defaults' => array(
        'bool' => TRUE,
        'string' => 'string',
        'array' => array('some value'),
      ),
    ),
    'cached' => array(
      'cache' => TRUE,
      'classes' => array(
        'handler',
      ),
    ),
    'not_cached' => array(
      'cache' => FALSE,
      'classes' => array(
        'handler',
      ),
    ),
    'big_hook_cached' => array(
      'cache' => TRUE,
      'use hooks' => TRUE,
      'classes' => array(
        'handler',
      ),
    ),
    'big_hook_not_cached' => array(
      'cache' => FALSE,
      'use hooks' => TRUE,
      'classes' => array(
        'handler',
      ),
    ),
  );
}

/**
 * Plugin callback.
 *
 * @see plugin_manager_plugin_test_plugin_manager_plugin_type()
 */
function plugin_manager_plugin_test_plugin_manager_plugin_test_big_hook_cached() {
  return array(
    'test1' => array(
      'function' => 'plugin_manager_plugin_test_hook_cached_test',
      'handler' => 'class1',
    ),
  );
}

/**
 * Plugin callback.
 *
 * @see plugin_manager_plugin_test_plugin_manager_plugin_type()
 */
function plugin_manager_plugin_test_plugin_manager_plugin_test_big_hook_not_cached() {
  return array(
    'test1' => array(
      'function' => 'plugin_manager_plugin_test_hook_not_cached_test',
      'class' => 'class1',
    ),
  );
}

/**
 * Callback for the big_hook_cached plugin.
 *
 * @see plugin_manager_plugin_test_plugin_manager_plugin_test_big_hook_cached
 */
function plugin_manager_plugin_test_hook_cached_test() {
}

/**
 * Callback for the big_hook_not_cached plugin.
 *
 * @see plugin_manager_plugin_test_plugin_manager_plugin_test_big_hook_not_cached()
 */
function plugin_manager_plugin_test_hook_not_cached_test() {
}
